import { motion, useScroll, useTransform } from 'framer-motion';
import { Link } from 'react-router-dom';
import {
  Sparkles,
  Wand2,
  Zap,
  Clock,
  Video,
  ImagePlus,
  Download,
  History,
  Star,
  ChevronDown,
  Check,
  Play,
} from 'lucide-react';
import { useState } from 'react';

const features = [
  {
    icon: Wand2,
    title: 'Text-to-Video',
    description: 'Transform any text prompt into a cinematic video. Our AI understands context, mood, and style.',
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    icon: ImagePlus,
    title: 'Image-to-Video',
    description: 'Upload any image and watch it come alive with motion, depth, and cinematic effects.',
    gradient: 'from-cyan-500 to-blue-500',
  },
  {
    icon: Zap,
    title: 'AI Prompt Enhancement',
    description: 'Our AI automatically enhances your prompts for better video quality and more accurate results.',
    gradient: 'from-yellow-500 to-orange-500',
  },
  {
    icon: Clock,
    title: 'Fast Generation',
    description: 'Generate videos in under 60 seconds. No waiting, no queues, instant creative power.',
    gradient: 'from-green-500 to-emerald-500',
  },
  {
    icon: Download,
    title: 'Download & Share',
    description: 'Download your videos in HD quality. Share directly to social media or use in your projects.',
    gradient: 'from-red-500 to-rose-500',
  },
  {
    icon: History,
    title: 'Generation History',
    description: 'Access all your previous generations. Re-download, remix, or build upon past creations.',
    gradient: 'from-violet-500 to-purple-500',
  },
];

const testimonials = [
  {
    name: 'Sarah Chen',
    role: 'Content Creator',
    avatar: 'SC',
    text: 'VidForge AI completely transformed my content workflow. I can now produce video content 10x faster than before.',
    rating: 5,
  },
  {
    name: 'Marcus Rivera',
    role: 'Marketing Director',
    avatar: 'MR',
    text: 'The quality is insane. Our ad creatives generated by VidForge outperform our traditional video content.',
    rating: 5,
  },
  {
    name: 'Aisha Patel',
    role: 'Indie Filmmaker',
    avatar: 'AP',
    text: 'As a filmmaker, I was skeptical. But VidForge AI is a legitimate creative tool. The prompt enhancement is chef\'s kiss.',
    rating: 5,
  },
];

const faqs = [
  {
    question: 'How does the credit system work?',
    answer: 'Each video generation costs 1 credit. Free users get 5 credits to start. Upgrade to Starter (100 credits) or Pro (500 credits) for more generations.',
  },
  {
    question: 'What video quality can I expect?',
    answer: 'Videos are generated in 576x320 resolution (standard) with plans to support HD. Each video is approximately 2-4 seconds long.',
  },
  {
    question: 'Can I use generated videos commercially?',
    answer: 'Yes! All videos generated on paid plans come with full commercial usage rights. Free tier videos are for personal use only.',
  },
  {
    question: 'How long does video generation take?',
    answer: 'Most videos are generated within 30-60 seconds. Complex prompts may take slightly longer. You can check real-time status in your dashboard.',
  },
  {
    question: 'What happens if generation fails?',
    answer: 'If a generation fails, your credit is automatically refunded. We also have retry logic to handle temporary API issues.',
  },
];

const pricingPlans = [
  {
    name: 'Free',
    price: '$0',
    credits: 5,
    description: 'Perfect for trying out AI video generation',
    features: ['5 video generations', 'Standard quality', 'Basic prompts', 'Community support', 'Watermarked videos'],
    cta: 'Get Started',
    popular: false,
  },
  {
    name: 'Starter',
    price: '$19',
    credits: 100,
    description: 'For creators who need more power',
    features: [
      '100 video generations',
      'HD quality',
      'AI prompt enhancement',
      'Priority support',
      'No watermarks',
      'Commercial license',
      'Image-to-video',
    ],
    cta: 'Start Creating',
    popular: true,
  },
  {
    name: 'Pro',
    price: '$49',
    credits: 500,
    description: 'For professionals and teams',
    features: [
      '500 video generations',
      'HD quality',
      'AI prompt enhancement',
      'Priority support',
      'No watermarks',
      'Commercial license',
      'Image-to-video',
      'API access',
      'Custom models',
    ],
    cta: 'Go Pro',
    popular: false,
  },
];

function FloatingOrb({ className }: { className: string }) {
  return (
    <div className={`absolute rounded-full blur-3xl opacity-20 animate-pulse ${className}`} />
  );
}

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border border-white/10 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between p-5 text-left hover:bg-white/5 transition-colors"
      >
        <span className="font-medium text-gray-200 pr-4">{question}</span>
        <ChevronDown
          className={`w-5 h-5 text-gray-400 flex-shrink-0 transition-transform duration-300 ${
            open ? 'rotate-180' : ''
          }`}
        />
      </button>
      <motion.div
        initial={false}
        animate={{ height: open ? 'auto' : 0 }}
        className="overflow-hidden"
      >
        <p className="px-5 pb-5 text-gray-400 leading-relaxed">{answer}</p>
      </motion.div>
    </div>
  );
}

export default function LandingPage() {
  const { scrollYProgress } = useScroll();
  const y = useTransform(scrollYProgress, [0, 1], [0, -50]);
  const [demoPlaying, setDemoPlaying] = useState(false);

  return (
    <div className="relative overflow-hidden">
      {/* Background Effects */}
      <div className="fixed inset-0 pointer-events-none">
        <FloatingOrb className="w-96 h-96 bg-purple-600 -top-48 -left-48" />
        <FloatingOrb className="w-96 h-96 bg-cyan-600 top-1/3 -right-48" />
        <FloatingOrb className="w-64 h-64 bg-pink-600 bottom-0 left-1/3" />
      </div>

      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center pt-20 pb-20 px-4">
        <motion.div style={{ y }} className="max-w-5xl mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 mb-8"
          >
            <Sparkles className="w-4 h-4 text-purple-400" />
            <span className="text-sm text-gray-300">Powered by Advanced AI Models</span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-bold leading-tight mb-6"
          >
            <span className="bg-gradient-to-r from-white via-gray-200 to-gray-400 bg-clip-text text-transparent">
              Create Cinematic
            </span>
            <br />
            <span className="bg-gradient-to-r from-purple-400 via-cyan-400 to-purple-400 bg-clip-text text-transparent">
              AI Videos
            </span>
            <br />
            <span className="bg-gradient-to-r from-white via-gray-200 to-gray-400 bg-clip-text text-transparent">
              in Seconds
            </span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-lg sm:text-xl text-gray-400 max-w-2xl mx-auto mb-10"
          >
            Transform your ideas into stunning videos with the power of AI.
            No editing skills needed — just describe what you want to see.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link
              to="/login?signup=true"
              className="group relative px-8 py-4 rounded-2xl bg-gradient-to-r from-purple-600 to-cyan-500 font-semibold text-lg overflow-hidden"
            >
              <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-cyan-400 opacity-0 group-hover:opacity-100 transition-opacity" />
              <span className="relative flex items-center gap-2">
                Start Creating — It's Free
                <Sparkles className="w-5 h-5" />
              </span>
            </Link>
            <button
              onClick={() => setDemoPlaying(true)}
              className="flex items-center gap-3 px-8 py-4 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors font-medium text-lg"
            >
              <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center">
                <Play className="w-4 h-4 ml-0.5" />
              </div>
              Watch Demo
            </button>
          </motion.div>

          {/* Demo Video Area */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="mt-16 relative"
          >
            <div className="relative rounded-2xl overflow-hidden border border-white/10 bg-gray-900/50 backdrop-blur-sm aspect-video max-w-4xl mx-auto">
              {demoPlaying ? (
                <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-purple-900/50 to-cyan-900/50">
                  <div className="text-center">
                    <div className="w-16 h-16 border-4 border-purple-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
                    <p className="text-gray-400">AI is generating your video...</p>
                  </div>
                </div>
              ) : (
                <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-purple-900/30 to-cyan-900/30">
                  <div className="text-center">
                    <Video className="w-16 h-16 text-gray-600 mx-auto mb-4" />
                    <p className="text-gray-500">Demo video preview</p>
                  </div>
                </div>
              )}
            </div>
            <div className="absolute -inset-4 bg-gradient-to-r from-purple-500/20 via-cyan-500/20 to-purple-500/20 rounded-3xl blur-2xl -z-10" />
          </motion.div>
        </motion.div>
      </section>

      {/* Features Section */}
      <section className="relative py-24 px-4">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl sm:text-5xl font-bold mb-4">
              <span className="bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
                Powerful Features
              </span>
            </h2>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto">
              Everything you need to create stunning AI-generated videos
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, i) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="group relative p-6 rounded-2xl bg-white/[0.02] border border-white/5 hover:border-white/10 transition-all duration-300 hover:bg-white/[0.04]"
              >
                <div
                  className={`w-12 h-12 rounded-xl bg-gradient-to-br ${feature.gradient} flex items-center justify-center mb-4`}
                >
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                <p className="text-gray-400 leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="relative py-24 px-4">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl sm:text-5xl font-bold mb-4">
              <span className="bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
                Loved by Creators
              </span>
            </h2>
            <p className="text-gray-400 text-lg">
              Join thousands of creators using VidForge AI
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <motion.div
                key={t.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="p-6 rounded-2xl bg-white/[0.02] border border-white/5"
              >
                <div className="flex items-center gap-1 mb-4">
                  {Array.from({ length: t.rating }).map((_, j) => (
                    <Star key={j} className="w-4 h-4 text-yellow-400 fill-yellow-400" />
                  ))}
                </div>
                <p className="text-gray-300 mb-6 leading-relaxed">"{t.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-purple-500 to-cyan-400 flex items-center justify-center text-sm font-bold">
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-medium">{t.name}</p>
                    <p className="text-sm text-gray-500">{t.role}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="relative py-24 px-4" id="pricing">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl sm:text-5xl font-bold mb-4">
              <span className="bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
                Simple Pricing
              </span>
            </h2>
            <p className="text-gray-400 text-lg">
              Start free, upgrade when you need more
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {pricingPlans.map((plan, i) => (
              <motion.div
                key={plan.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className={`relative p-8 rounded-2xl ${
                  plan.popular
                    ? 'bg-gradient-to-b from-purple-500/10 to-cyan-500/10 border-2 border-purple-500/30'
                    : 'bg-white/[0.02] border border-white/5'
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 rounded-full bg-gradient-to-r from-purple-600 to-cyan-500 text-xs font-semibold">
                    Most Popular
                  </div>
                )}
                <h3 className="text-xl font-bold mb-2">{plan.name}</h3>
                <div className="flex items-baseline gap-1 mb-2">
                  <span className="text-4xl font-bold">{plan.price}</span>
                  <span className="text-gray-500">/month</span>
                </div>
                <p className="text-sm text-gray-400 mb-6">{plan.description}</p>
                <div className="flex items-center gap-2 mb-6 px-3 py-2 rounded-lg bg-white/5 inline-block">
                  <Zap className="w-4 h-4 text-yellow-400" />
                  <span className="text-sm font-medium">{plan.credits} credits/month</span>
                </div>
                <ul className="space-y-3 mb-8">
                  {plan.features.map(f => (
                    <li key={f} className="flex items-center gap-2 text-sm text-gray-300">
                      <Check className="w-4 h-4 text-green-400 flex-shrink-0" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Link
                  to="/login?signup=true"
                  className={`block w-full py-3 rounded-xl text-center font-semibold transition-all ${
                    plan.popular
                      ? 'bg-gradient-to-r from-purple-600 to-cyan-500 hover:shadow-lg hover:shadow-purple-500/25'
                      : 'bg-white/5 border border-white/10 hover:bg-white/10'
                  }`}
                >
                  {plan.cta}
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="relative py-24 px-4">
        <div className="max-w-3xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl sm:text-5xl font-bold mb-4">
              <span className="bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
                FAQ
              </span>
            </h2>
            <p className="text-gray-400 text-lg">
              Frequently asked questions about VidForge AI
            </p>
          </motion.div>

          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
              >
                <FAQItem question={faq.question} answer={faq.answer} />
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="relative py-24 px-4">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-4xl mx-auto text-center relative"
        >
          <div className="p-12 rounded-3xl bg-gradient-to-b from-purple-500/10 to-cyan-500/10 border border-white/10 relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-r from-purple-500/5 to-cyan-500/5" />
            <div className="relative z-10">
              <h2 className="text-3xl sm:text-4xl font-bold mb-4">
                Ready to Create Amazing Videos?
              </h2>
              <p className="text-gray-400 text-lg mb-8 max-w-xl mx-auto">
                Join thousands of creators already using VidForge AI. Start with 5 free credits — no credit card required.
              </p>
              <Link
                to="/login?signup=true"
                className="inline-flex items-center gap-2 px-8 py-4 rounded-2xl bg-gradient-to-r from-purple-600 to-cyan-500 font-semibold text-lg hover:shadow-lg hover:shadow-purple-500/25 transition-all"
              >
                Get Started Free
                <Sparkles className="w-5 h-5" />
              </Link>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="relative py-12 px-4 border-t border-white/5">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500 to-cyan-400 flex items-center justify-center">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
              <span className="font-bold bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
                VidForge AI
              </span>
            </div>
            <div className="flex items-center gap-6 text-sm text-gray-500">
              <a href="#" className="hover:text-gray-300 transition-colors">Privacy</a>
              <a href="#" className="hover:text-gray-300 transition-colors">Terms</a>
              <a href="#" className="hover:text-gray-300 transition-colors">Contact</a>
            </div>
            <p className="text-sm text-gray-600">
              © 2026 VidForge AI. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
